### PR TITLE
Added support for wildcards in hostnames

### PR DESCRIPTION
**Pull request by mirbuf**
This would allow us to specify domain* or *domain or even * as hostname (to allow opening in new tab for all domains).

### CODE REVIEW

**Comment by ramkumar-kr** [comment]
Hi,
Your patch works really well. Thanks a lot for  contributing.

However, the browser action popup must also tell the user if a wildcard is being used.

Here is a screenshot on how it would look in firefox and chrome -

*Firefox*
Firefox

*Chrome*
Chrome

I will send a pull request to your fork containing these changes. You can merge them and we can then merge this pull request

**Comment by ramkumar-kr** [comment]
https://github.com/mirbuf/open-in-new-tab/pull/1

**Comment by mirbuf** [comment]
I see. Nice improvement. I'd like to test it, but cannot install unsigned extensions under windows/firefoxportable 52.3 stable. Can you give me some directions to bypass the signed extension check in order to test it before committing any change?

**Comment by ramkumar-kr** [comment]
I use the [`web-ext`](https://github.com/mozilla/web-ext) tool to test the extension for firefox.

**Comment by olivercarl** [comment]
Would it be possible to extend the feature to bookmarks? I am used that bookmarks always open a new tab (but that extension is no longer supported in 57)...

**Comment by AndrewDavis** [comment]
I second olivercarl's request for opening bookmarks in new tabs. I really miss this feature and it keeps messing up my browsing because I lose open tabs on accident.

**Comment by ramkumar-kr** [comment]
I just released version 0.0.9 which allows the user to configure to open bookmarks in new tabs in the addon preferences thanks to [https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserSettings/openBookmarksInNewTabs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserSettings/openBookmarksInNewTabs). Available in Firefox 59 and above.

@olivercarl  @AndrewDavis

**Comment by redrockboy** [comment]
Thank you for this extension!  I just made a contribution via Mozilla.  I'm using this extension with Firefox 66.  For those who use this extension globally (with the *.* option), a blacklist would be very helpful, since not all websites work well with the extension, like youtube.com.  For example, clicking on the vertical ellipsis in YouTube opens a new blank tab.  It would be better if the user could just blacklist such sites.

**Pull request merged**
